name: 'Notify Teams Channel'
auther: 'preetul.correia@genmills.com'
description: 'It will sent the message in MS Teams Channel about the status of the job'
inputs:
  webhook_uri:
     description: 'Web hook ULR for the MS Teams Channel to receive the message'
     required: true
  message:
     description: 'Message to be posted in MS Teams Channel'
     required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  arges:
   - ${{  input.webhook_uri }}
   - ${{  input.message }}